### ISSUE TITLE
游戏语音会自动切换回中文？

### ISSUE THREAD

**Issue by tianxulan** [DawnFz/Genshin.Launcher.Plus#44]
通过启动器启动游戏会overwrite游戏默认语言，比如从日语退出再从启动器进入语言会自动切换为中文。

**Comment by DawnFz** [comment]
如果你在进入游戏时候使用了账号切换的功能就会使用你保存所选账号时的设置，保存的账号文件包含了账号数据与保存时的游戏设置，如果你想更新已保存账号的设置，同名覆盖保存即可
