### ISSUE TITLE
无法正常显示账号切换器

### ISSUE THREAD

**Issue by jswnlinyu** [DawnFz/Genshin.Launcher.Plus#45]
https://user-images.githubusercontent.com/53430542/160961265-0ebb8d58-62fa-4745-ace1-ce59ded1bb2d.mp4

**Comment by DawnFz** [comment]
我这里没有成功复现这个问题，请提供一下复现的方法

**Comment by jswnlinyu** [comment]
好吧，我也不知道如何复现，我每一次打开都存在这个问题。我的系统版本是win10 1909（18363.592）
分辨率是1366x768，你试一试是不是分辨率的问题。谢谢大佬了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2022年3月31日 14:29
收件人: ***@***.***>
抄送: Daniel ***@***.***>; ***@***.***>
主题: Re: [DawnFz/Genshin.Launcher.Plus] 无法正常显示账号切换器 (Issue #45)


我这里没有成功复现这个问题，请提供一下复现的方法

―

**Comment by DawnFz** [comment]
![image](https://user-images.githubusercontent.com/19362176/160991456-130179b1-6487-47fc-8eb1-2924619cac93.png)

**Comment by jswnlinyu** [comment]
重启电脑之后恢复了正常，打扰大佬了
