### ISSUE TITLE
Version 1.3.9.5 Not opening

### ISSUE THREAD

**Issue by ReaperCalli** [DawnFz/Genshin.Launcher.Plus#46]
![image](https://user-images.githubusercontent.com/59681368/161273123-5f5ab19d-5953-4765-90e4-085fb67be4e2.png)
Hello I am not able to use the application after the new version it shows this on the task manager then closes itself. Thank you for your hard work I have been enjoying the launcher so far.

**Comment by DawnFz** [comment]
The program works fine on some people's computers, but some people's don't, I'm investigating the cause

**Comment by DawnFz** [comment]
It has been fixed in the new version, you can manually download the exe file on the release page to replace it, sorry for the inconvenience
