### ISSUE TITLE
建议把Dotnet运行时链接放在更新里，或者其他更明显的地方

### ISSUE THREAD

**Issue by chenchenick** [DawnFz/Genshin.Launcher.Plus#48]
辛苦大佬，提个建议啊

高版本的dotnet runtime很少有人有，需要主动安装。
懂得人当然没问题，小白第一次用的话很容易碰到因为缺少运行时而无法运行的问题。
我换一台机器用就忘了这事，还是回原帖里看回复才知道。
建议把Dotnet运行时链接放在更新里，或者其他更明显的地方
谢谢

**Comment by DawnFz** [comment]
建议收到
