### ISSUE TITLE
[Info] Game Client folder structure error 31-4302

### ISSUE THREAD

**Issue by Motias-git** [DawnFz/Genshin.Launcher.Plus#50]
### Do not put the Launcher files in the _\Genshin Impact\Genshin Impact Game\Launcher_ , this causes error **31-4302** 

Becouse of the "Launcher" folder with a file inside called "any.exe" in the directory:
_\Genshin Impact\Genshin Impact Game\Launcher\any.exe_
**This path is used in the game client by default**

**Comment by DawnFz** [comment]
The game will loading all "DLL" files and "exe" files in the game directory when starting. when there is an external program that cannot be loaded, it will report error "31-4302"
