### ISSUE TITLE
“保存上次登录的账号数据”BUG

### ISSUE THREAD

**Issue by Phycanva** [DawnFz/Genshin.Launcher.Plus#53]
输入文件名为空时程序崩溃，请补全异常输入判断的逻辑

**Comment by DawnFz** [comment]
我去看了下，老版本（前两个）是有的，可能是上两个版本优化的时候不小心“优化掉了”，抱歉给你带来使用上的不便，这个问题下个版本将会修复
![QQ图片20220426131116.png](https://s2.loli.net/2022/04/26/TFCkvjiqaudDZAJ.png)
