### ISSUE TITLE
保存不了游戏内设置

### ISSUE THREAD

**Issue by cy3z** [DawnFz/Genshin.Launcher.Plus#54]
每次进游戏都是同样的设置，图像、音频之类的设置手动修改后下次启动还是不会保留之前的设置，不清楚是不是启动器的问题

**Comment by DawnFz** [comment]
使用了账号保存会同时将当前游戏内的设置情况一并保存入账号文件中，在使用了账号切换功能后会将账号文件中的设置内容一并切换，如果想要更新设置可以将游戏设置成想要的效果之后输入相同的账号文件名覆盖保存。如果没有使用该功能出现你所描述的内容的话是其他原因造成的，得自行检查

**Comment by cy3z** [comment]
谢谢，我确实设置了多账号登录，经过重新设置已经解决了
