### ISSUE TITLE
关于背景

### ISSUE THREAD

**Issue by 3360891395** [DawnFz/Genshin.Launcher.Plus#55]
你好开发者，能不能做一个保存网络背景的功能或者展示图片来源
![2bc40efe8a1550a7d5c09b4eb5f6c28](https://user-images.githubusercontent.com/32975424/166093170-ea99705f-819e-4da4-a861-c00e79a61b3a.png)

**Comment by KargathEx** [comment]
我是来看看有没有介绍性文档的，怎么不知不觉就开始搜[萌图](https://chan.sankakucomplex.com/ru/post/show/24415348)了...

**Comment by DawnFz** [comment]
下个版本加入该功能

**Comment by 3360891395** [comment]
> 

我超太厉害了

**Comment by 1061875478** [comment]
能分享一下图源吗，我想直接加到壁纸软件自动推送

**Comment by DawnFz** [comment]
> 能分享一下图源吗，我想直接加到壁纸软件自动推送

图源是Pixiv，不是根据固定的Api来进行获取的，是我自己实现的一个方式，具体你可以参考 https://github.com/DawnFz/Genshin.Launcher.Plus/blob/main/GenShin_Launcher_Plus/Service/MainService.cs#L29 这个方法
