### ISSUE TITLE
主界面启动后没有居中显示

### ISSUE THREAD

**Issue by vsouild** [DawnFz/Genshin.Launcher.Plus#56]
![](https://user-images.githubusercontent.com/20264381/166222576-5c761a18-ebbb-4663-a347-29c7b6817274.png)
Setting.ini配置文件里的初始参数非整数
```ini
MainHeight=730.0840336134454
MainWidth=1280.2689075630253
```

**Comment by DawnFz** [comment]
已解决，下个推送版本修复
