### ISSUE TITLE
config.ini 文件多余的配置项导致转换失败

### ISSUE THREAD

**Issue by sjlei** [DawnFz/Genshin.Launcher.Plus#57]
为什么会多出来一块配置？跟我原先是B服游戏客户端有关系吗？

![image](https://user-images.githubusercontent.com/34293221/166656041-d38846c3-f5f1-4b55-bd37-f06757c0f2fe.png)

![image](https://user-images.githubusercontent.com/34293221/166655573-74c35e23-feae-4936-a4be-1214fcb0f0cc.png)

**Comment by DawnFz** [comment]
这段配置本不该存在此处，也不是原p生成的，这段配置是官方启动器用的，应该在官方启动器目录下的config.ini中，建议你自行检查游戏目录是否正常

**Comment by sjlei** [comment]
我检查过了，第二个截图，是Genshin Impact Game目录。我把官方启动器什么的全都关了，重启电脑后也还是会这样。删掉这段多余的配置还是会自动加上。每次都会加，我一会录个视频看看
![image](https://user-images.githubusercontent.com/34293221/166658384-ad854a76-030d-4252-95bb-d6e81a1b741c.png)

**Comment by sjlei** [comment]
游戏启动后是官服
https://user-images.githubusercontent.com/34293221/166659281-a323d6ec-0ca2-4703-8447-86efaac17adc.mp4

**Comment by DawnFz** [comment]
这我不清楚，肯定不是原p加上去的，我代码里都没写这些字段，按你视频里的效果，即使不使用原p，手动打开原神应该也会有，我也不清楚原因，这个你只能自己排查

**Comment by DawnFz** [comment]
是官服的话是因为游戏启动时Config.ini里的内容被加载进了YuanShen.exe，但是原神不会判断这两个节，哪个在前面就会加载哪个

**Comment by sjlei** [comment]
我刚试了下，直接打开游戏就没加这段配置

https://user-images.githubusercontent.com/34293221/166661023-5e124fbe-8d25-4375-92c3-c9c9ea3f284b.mp4

确定不是启动器的问题的话，那确实很奇怪了，应该跟我原先是B服游戏客户端有一定的关系，我重新从官网下载一个再试试吧。
也有可能是之前使用过其他人写的切换器的问题，总之我先下一个纯净的客户端试试吧

**Comment by DawnFz** [comment]
九成是其他切换器的锅，例如代码没写好把config.ini的编码改了或者加bom了，你可以试试找别人要一个正常的config.ini替换进去

**Comment by sjlei** [comment]
果然是其他切换器把游戏损坏了，我重新下载了一个游戏，使用原P官B服来回切换正常，但是把新下载的config.ini复制到老的目录里面还是有问题，只能是游戏本体出现问题了😂
太坑了，还是大佬写的切换器牛B，主要是能记录账号这个功能很棒，不然每次切换成官服后还得再登录。

对了，提个小建议，如果保存的账号能配置对应的服务器就好了，比如切换账号自动切换成对应的服务器，非常感谢

**Comment by Lightczx** [comment]
> 果然是其他切换器把游戏损坏了，我重新下载了一个游戏，使用原P官B服来回切换正常，但是把新下载的config.ini复制到老的目录里面还是有问题，只能是游戏本体出现问题了😂 太坑了，还是大佬写的切换器牛B，主要是能记录账号这个功能很棒，不然每次切换成官服后还得再登录。
> 
> 对了，提个小建议，如果保存的账号能配置对应的服务器就好了，比如切换账号自动切换成对应的服务器，非常感谢

所以其他切换器具体是哪个？🥲

**Comment by sjlei** [comment]
> 所以其他切换器具体是哪个？🥲

这是我之前用过的切换器
![185731](https://user-images.githubusercontent.com/34293221/166668840-5a1f9ff4-bd9e-4bda-bf1a-1814923239f0.png)

**Comment by Lightczx** [comment]
有任何的开源地址或者下载地址么

**Comment by sjlei** [comment]
> 有任何的开源地址或者下载地址么

没有开源项目，下载甚至还需要去B站私信才给链接，很奇怪的
（1）原神官服\B服互转切换器：
百度网盘：https://pan.baidu.com/s/1NyyhwStgqs5eBbNOx132ag 提取码:q3w9
吼姆盘：https://www.homuhomu.cn/pan/

![image](https://user-images.githubusercontent.com/34293221/166669946-6cb7278e-82cb-4340-989c-5969240855bd.png)
