### ISSUE TITLE
Response status code does not indicate success:403(Forbidden)

### ISSUE THREAD

**Issue by mawMOBai** [DawnFz/Genshin.Launcher.Plus#58]
ID:20220504
Response status code does not indicate success:403(Forbidden)

每次打开都有这个报错 但是貌似又没什么影响？

**Comment by DawnFz** [comment]
可能你的IP被每日一图的API拉黑了
或者是你在短时间请求了很多次每日一图的API导致的

**Comment by DawnFz** [comment]
可能你的IP被每日一图的API拉黑了
或者是你在短时间请求了很多次每日一图的API导致的
