### ISSUE TITLE
国际服切换成国服后内存爆炸，并无法启动客户端

### ISSUE THREAD

**Issue by DivinationHW** [DawnFz/Genshin.Launcher.Plus#62]
![5~P8HX9NRIXU)A$PQKQR2BG](https://user-images.githubusercontent.com/107331343/173211279-e11e6bfc-bf33-4158-a4b0-67f73448a51d.png)

**Comment by 1061875478** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
