### ISSUE TITLE
B服登录提示数据异常问题

### ISSUE THREAD

**Issue by levebo** [DawnFz/Genshin.Launcher.Plus#68]
下载的国服客户端 切换成B服提示数据异常  是今天下午玩游戏，突然提示后就不能登录了
![image](https://user-images.githubusercontent.com/71813892/179735728-d74c2ce7-3178-44ee-a8db-1102d01adbaa.png)

- [ ] 

- [ ] #

**Comment by ParcoHan** [comment]
两天了，国际服，国服都正常，就是转换B服时报错！

**Comment by DawnFz** [comment]
已经尝试在新版本中修复
