### ISSUE TITLE
Epic 国际服转换国服时的三个文件错误

### ISSUE THREAD

**Issue by escape0707** [DawnFz/Genshin.Launcher.Plus#70]
重点是这三个文件：

```
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\mhyprot3.Sys 备份失败：原因： Cannot create a file when that file already exists.
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\mhyprot2.Sys 备份失败：原因： Cannot create a file when that file already exists.
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\Audio_Chinese_pkg_version 文件不存在，备份失败，跳过
```

我也不知道为什么我下下来的国际服文件里自带前两个 `Sys` 文件的 `.bak`，我彻底重新装的。

另外我下载的国际服里面的文件是 `Audio_English(US)_pkg_version`，即使我已经在游戏中调成日文日语。不过我国际服下载下载的时候确实默认是英语，不知道是否和 Epic 启动器设置的语言有关。总之不是英文，希望 Owner 能够把这个文件的备份逻辑单独处理一下。

这三个文件由于备份出错，我无法方便的还原。

转换之后登陆时会出现 `31-4302` 错误，将上述三文件移除后错误仍然呈现，校验文件后需要下载 `8177.95MB`。下载后错误仍然呈现。

<details>
    <summary>全部日志内容</summary>
    <pre>
备用PKG转换资源下载地址及访问密码: etxd
https://pan.baidu.com/s/1-5zQoVfE7ImdXrn8OInKqg
GenshinImpact_Data/app.info .bak 文件不存在，启动器将尝试下一步操作，若无反应请重新下载资源文件！
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/app.info 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/globalgamemanagers 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/globalgamemanagers.assets 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/globalgamemanagers.assets.resS 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/upload_crash.exe 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Managed/Metadata/global-metadata.dat 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Native/Data/Metadata/global-metadata.dat 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Native/UserAssembly.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Native/UserAssembly.exp 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Native/UserAssembly.lib 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/ZFProxyWeb.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/ZFEmbedWeb.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/zf_cef.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/Rewired_DirectInput.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/metakeeper.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/libUbiCustomEvent.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/libGLESv2.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/libEGL.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/chrome_elf.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/cri_mana_vpx.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/cri_vip_unity_pc.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/cri_ware_unity.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/d3dcompiler_47.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/hdiffz.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/hpatchz.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/mihoyonet.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/Mmoron.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/MTBenchmark_Windows.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/NamedPipeClient.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/UnityNativeChromaSDK.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/UnityNativeChromaSDK3.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/Plugins/xlua.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact_Data/StreamingAssets/20527480.blk 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\mhyprot3.Sys 备份失败：原因： Cannot create a file when that file already exists.
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\mhyprot2.Sys 备份失败：原因： Cannot create a file when that file already exists.
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\Audio_Chinese_pkg_version 文件不存在，备份失败，跳过
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\pkg_version 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\UnityPlayer.dll 备份成功
C:\Program Files\Epic Games\GenshinImpact\Genshin Impact game\GenshinImpact.exe 备份成功
YuanShen_Data/app.info 替换成功
YuanShen_Data/globalgamemanagers 替换成功
YuanShen_Data/globalgamemanagers.assets 替换成功
YuanShen_Data/globalgamemanagers.assets.resS 替换成功
YuanShen_Data/upload_crash.exe 替换成功
YuanShen_Data/Managed/Metadata/global-metadata.dat 替换成功
YuanShen_Data/Native/Data/Metadata/global-metadata.dat 替换成功
YuanShen_Data/Native/UserAssembly.dll 替换成功
YuanShen_Data/Native/UserAssembly.exp 替换成功
YuanShen_Data/Native/UserAssembly.lib 替换成功
YuanShen_Data/Plugins/ZFProxyWeb.dll 替换成功
YuanShen_Data/Plugins/ZFEmbedWeb.dll 替换成功
YuanShen_Data/Plugins/zf_cef.dll 替换成功
YuanShen_Data/Plugins/Rewired_DirectInput.dll 替换成功
YuanShen_Data/Plugins/metakeeper.dll 替换成功
YuanShen_Data/Plugins/libUbiCustomEvent.dll 替换成功
YuanShen_Data/Plugins/libGLESv2.dll 替换成功
YuanShen_Data/Plugins/libEGL.dll 替换成功
YuanShen_Data/Plugins/chrome_elf.dll 替换成功
YuanShen_Data/Plugins/cri_mana_vpx.dll 替换成功
YuanShen_Data/Plugins/cri_vip_unity_pc.dll 替换成功
YuanShen_Data/Plugins/cri_ware_unity.dll 替换成功
YuanShen_Data/Plugins/d3dcompiler_47.dll 替换成功
YuanShen_Data/Plugins/hdiffz.dll 替换成功
YuanShen_Data/Plugins/hpatchz.dll 替换成功
YuanShen_Data/Plugins/mihoyonet.dll 替换成功
YuanShen_Data/Plugins/Mmoron.dll 替换成功
YuanShen_Data/Plugins/MTBenchmark_Windows.dll 替换成功
YuanShen_Data/Plugins/NamedPipeClient.dll 替换成功
YuanShen_Data/Plugins/UnityNativeChromaSDK.dll 替换成功
YuanShen_Data/Plugins/UnityNativeChromaSDK3.dll 替换成功
YuanShen_Data/Plugins/xlua.dll 替换成功
YuanShen_Data/StreamingAssets/20527480.blk 替换成功
mhyprot3.Sys 替换成功
mhyprot2.Sys 替换成功
Audio_Chinese_pkg_version 替换成功
pkg_version 替换成功
UnityPlayer.dll 替换成功
YuanShen.exe 替换成功
转换完成，您可以启动游戏了~
</pre>

**Comment by 1061875478** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by escape0707** [comment]
并且转换之后会出现 `31-4302` 错误。

**Comment by escape0707** [comment]
将上述三文件移除出去错误仍然出现，校验文件后需要下载 8GB。

**Comment by DawnFz** [comment]
暂时不支持EPIC的原神客户端转换，抱歉
