### ISSUE TITLE
开启”启动游戏后关闭本程序“后，启动器窗口大小异常重置

### ISSUE THREAD

**Issue by ChrisKimZHT** [DawnFz/Genshin.Launcher.Plus#73]
版本：1.5.1.0
开启 `启动游戏后关闭本程序` 后再启动游戏，下次打开启动器，窗口大小会重置为 840*500。猜测启动器自身关闭时没有正确保存配置文件内的 `MainWidth` 和 `MainHeight` 条目。

**Comment by DawnFz** [comment]
已在新版本中尝试修复该问题
