### ISSUE TITLE
软件内置及官网的Pkg下载链接过期&下载进度有小问题

### ISSUE THREAD

**Issue by Patrick-Ze** [DawnFz/Genshin.Launcher.Plus#77]
**1. 使用软件内置的下载Pkg按钮时**，下载链接指向 `https://resource.snapgenshin.com/Plugins/Genshin.Launcher.Plus.SE.Plugin/`
![image](https://user-images.githubusercontent.com/19711799/193297320-a1391fda-682f-4cfa-9324-f8386835a076.png)
此链接内的Pkg包停留在2022-08-25
![image](https://user-images.githubusercontent.com/19711799/193297485-63737e13-4aad-4826-8c96-1a4ecaf30eca.png)

**2. 使用软件内置提示的百度网盘链接时**，下载链接指向 `https://pan.baidu.com/s/1-5zQoVfE7ImdXrn8OInKqg`
此链接内的Pkg包停留在 2022-05-31
![image](https://user-images.githubusercontent.com/19711799/193298227-82e4b47e-558e-4a26-bfca-49ac58dd6331.png)
**官网的下载链接也用的是同一个百度网盘链接**
![image](https://user-images.githubusercontent.com/19711799/193298688-b349e118-f5b0-44a4-aa83-b8148afd6bf8.png)

**3. 下载进度的显示百分比与进度条进度不匹配（不影响使用）：**
可以看到65%时进度条已经快要完成
![Snipaste_2022-09-30_22-39-27](https://user-images.githubusercontent.com/19711799/193298037-f8e924b0-7e45-4ad3-9671-a71958c4a2a2.png)
超出一定进度后进度条不再更新
![Snipaste_2022-09-30_22-40-11](https://user-images.githubusercontent.com/19711799/193298123-67659ed2-5061-44c6-bc05-5736e07a600c.png)
编辑：我的显示缩放设置为125%，不知道有没有影响。不过这个小问题不影响使用

**Comment by DawnFz** [comment]
收到,这两天我统一解决一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DawnFz/Genshin.Launcher.Plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 晚上10:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[DawnFz/Genshin.Launcher.Plus] 软件内置及官网的Pkg下载链接过期&amp;下载进度有小问题 (Issue #77)





  
 
使用软件内置的下载Pkg按钮时，下载链接指向 https://resource.snapgenshin.com/Plugins/Genshin.Launcher.Plus.SE.Plugin/
 
 此链接内的Pkg包停留在2022-08-25
 
 
 
 
使用软件内置提示的百度网盘链接时，下载链接指向 https://pan.baidu.com/s/1-5zQoVfE7ImdXrn8OInKqg
 此链接内的Pkg包停留在 2022-05-31
 
 
 
 
下载进度的显示百分比与进度条进度不匹配：
 可以看到65%时进度条已经快要完成
 
 超出一定进度后进度条不再更新

**Comment by huangxiongfei666** [comment]
大佬 我也是发现两个地址的 pkg包都过期了 现在[3.1.0-2的包找不到 转化不了 麻烦大佬看一眼谢谢
