### ISSUE TITLE
更新1.5.4版本后，转换客户端时，持续弹出下载转换包页面（百度云）

### ISSUE THREAD

**Issue by ArthurGXY** [DawnFz/Genshin.Launcher.Plus#87]
转换包（3.2.0-1) 已经从交流群里获取，还有另一位群友貌似通过重新安装启动器成功转换，重装前也有此问题。
![image](https://user-images.githubusercontent.com/22321345/199427870-c81ca17b-f3c5-4687-939d-96f95833af6b.png)

**Comment by DawnFz** [comment]
已在1.5.4.1修复
