### ISSUE TITLE
Toggl english translation 

### ISSUE THREAD

**Issue by wafflebot2143** [DawnFz/Genshin.Launcher.Plus#92]
I know from browsing the other issues that that an english translation for this launcher exists, but I cannot figure out how to toggle it. Can someone please tell me how?

**Comment by DawnFz** [comment]
![QQ20221123000311.jpg](https://s2.loli.net/2022/11/23/Oi4WjgVMY3c7a5y.jpg)
![QQ20221123000322.jpg](https://s2.loli.net/2022/11/23/3gPSEZyLDTsIC1Y.jpg)

**Comment by Lightczx** [comment]
@DawnFz 做个首次启动选语言的引导呗
