### ISSUE TITLE
更新pkg下载链接

### ISSUE THREAD

**Issue by idhaname** [DawnFz/Genshin.Launcher.Plus#97]
原先的[pkg下载链接](https://resource.snapgenshin.com/Plugins/Genshin.Launcher.Plus.SE.Plugin/)因为snapgenshin的转服插件停止维护，现在无法访问
我交了一个pr #96 ，更新了设置-客户端转换-下载pkg文件的按钮指向的链接，不过还没有进行测试
希望各位大佬们能帮忙看下，如果没问题的话就帮忙通过一下啦w

**Comment by Lightczx** [comment]
用 胡桃 去

**Comment by Lightczx** [comment]
GLP已经不再维护了

**Comment by idhaname** [comment]
不再维护的话不应该在readme上写一下"该项目不再维护"之类的吗？

**Comment by Lightczx** [comment]
懒（

**Comment by idhaname** [comment]
6，那我关issue了
